- config/environments/development.rb
- config/environments/test.rb
- config/locales/en.yml
- config/quick_search_config.yml
These workarounds fix the hanging application. Depends on #19
> Bring back to life

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/highlighted_facet.scss
- app/services/abstract_search_service.rb
- app/services/article_search_service.rb
- app/services/catalog_search_service.rb
- app/views/quick_search/search/_highlighted_facet.html.erb
- app/views/quick_search/search/_module.html.erb
- spec/services/abstract_search_service_spec.rb
- spec/views/quick_search/search/_highlighted_facet.html.erb_spec.rb
> Add facets for article & catalog bento results

- config/deploy/prod.rb
This PR depends on https://github.com/sul-dlss/operations-tasks/issues/778 to work properly (config/secrets.yml isn't on the prod boxes).
> add prod environment for capistrano

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
depends on https://github.com/sul-dlss/shared_configs/pull/371
> add honeybadger

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/foundation_compatibility.scss
> adds foundation compatibility classes

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/online-label.scss
- app/services/abstract_search_service.rb
- app/services/article_search_service.rb
- app/views/quick_search/search/_result_details.html.erb
- spec/services/article_search_service_spec.rb
- spec/views/quick_search/search/_result_details.html.erb_spec.rb
Closes #30 
_**Note:** This will require a change to the SearchWorks API that I'm working on._
> Update article search result details

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/base.scss
- app/assets/stylesheets/results.scss
- app/views/quick_search/search/_module.html.erb
- app/views/quick_search/search/_module_heading.html.erb
- app/views/quick_search/search/_result.html.erb
- config/locales/en.yml
> Stylin results 😎

- app/views/quick_search/search/index.html.erb
- config/quick_search_config.yml
This PR is connected to #55. Requires #43 to complete.
> reorder bentos to catalog, articles

- app/searchers/quick_search/library_website_searcher.rb
- app/services/abstract_search_service.rb
- app/services/library_website_search_service.rb
- app/views/quick_search/search/_module.html.erb
- app/views/quick_search/search/_see_all.html.erb
- app/views/quick_search/search/index.html.erb
- config/locales/en.yml
- config/quick_search_config.yml
- config/settings.yml
- spec/fixtures/library.stanford.edu/1.html
- spec/searchers/quick_search/library_website_searcher_spec.rb
- spec/services/library_website_search_service_spec.rb
This PR fixes #3. It's based on screen scraping so it's fragile. An API-based solution is being investigated...
> library website searches based on screen scraping

- app/views/layouts/quick_search/_found_types.html.erb
- config/locales/en.yml
> update sub_heading_html for website and use short names for top Result counts

- app/services/library_website_search_service.rb
- app/views/quick_search/search/_no_results.html.erb
- config/locales/en.yml
> customize the No Results partial

- app/assets/stylesheets/base.scss
- app/assets/stylesheets/quick_search_overrides.scss
- app/views/layouts/quick_search/_search_form.html.erb
> Nix search-btn class in favor of our mixin

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
Fixes https://github.com/sul-dlss/SearchWorks/issues/1811.
> Remove turbolinks

- app/views/layouts/quick_search/application.html.erb
Fixes #163 
Does not remove current GA so we can keep current custom events. See https://github.com/sul-dlss/sul-bento-app/issues/163#issuecomment-437100174
> add Google Tag Manager tracking code

- app/assets/stylesheets/modules/homepage.scss
- app/views/quick_search/pages/home.html.erb
> Card deck layout

- app/views/quick_search/pages/home.html.erb
> Add an empty alt tag and role=presentation to the home page images

- app/views/quick_search/pages/home.html.erb
- app/views/quick_search/search/index.html.erb
- config/locales/en.yml
> Add title content

- app/assets/stylesheets/modules/global-footer.scss
- app/assets/stylesheets/modules/sul-footer.scss
- app/assets/stylesheets/sul-variables.scss
- app/views/layouts/quick_search/application.html.erb
- app/views/shared/_global_footer.html.erb
> Update SU footer

- config/locales/en.yml
> Update the global alert content.

- config/locales/en.yml
> Update covid alert

- app/views/shared/_services_menu.html.erb
Part of https://github.com/sul-dlss/SearchWorks/issues/2428
Fixes https://github.com/sul-dlss/sul-bento-app/issues/254
> Update purchase url

- config/locales/en.yml
Part of sul-dlss/SearchWorks#2442
> Update wording for the COVID global alert.

- config/locales/en.yml
Part of sul-dlss/SearchWorks#2474
> Update link in global alert.

- app/assets/stylesheets/modules/skip-links.scss
- app/assets/stylesheets/sul-bento.scss
- app/views/layouts/quick_search/application.html.erb
- spec/views/layouts/quick_search/application.html.erb_spec.rb
> Fixes #287 adds working skip links

- app/views/quick_search/search/index.html.erb
- app/views/shared/_services_menu.html.erb
> Accessibility tweaks

- app/assets/stylesheets/base.scss
- app/assets/stylesheets/bootstrap-variables.scss
- app/assets/stylesheets/modules/results.scss
- app/assets/stylesheets/modules/top-navbar.scss
> Set the font-size-base to 15px

- app/services/article_search_service.rb
> Update metadata used for Articles+ results.

- app/views/layouts/quick_search/_found_types.html.erb
- app/views/quick_search/search/_module.html.erb
- app/views/quick_search/search/index.html.erb
- config/application.rb
- config/locales/en.yml
- config/quick_search_config.yml
- config/settings.yml
- config/settings/test.yml
> Add lib guides link (w/ count) to the "Found results in" links section

- app/views/quick_search/search/_see_all.html.erb
- spec/features/searcher_anchors_spec.rb
> Add some context to results buttons

- app/assets/javascripts/yewno.js
Is there any reason to make a setting out of this? 🤞, hope not...
> Set the yewno url prefix, fixes #194

- config/initializers/okcomputer.rb
- config/routes.rb
> Add (optional) okcomputer checks for the searcher endpoints; fixes #106

- config/settings.yml
- spec/features/exhibits_spec.rb
- spec/searchers/quick_search/exhibits_searcher_spec.rb
- spec/searchers/quick_search/lib_guides_searcher_spec.rb
Reviewed some feedback from JV + designs
> Set exhibits and libguides results to 3

- app/views/layouts/quick_search/_found_types.html.erb
> Move the aria-label up to the nav

- LICENSE
> Add the current Stanford license.

- config/locales/en.yml
> Update global message for air quality closure

- Gemfile.lock
Updating outside of the dependency update cycle because this was blocking deploys!
> Update honeybadger gem

- config/settings.yml
These are out in production today! 😌
> Add LibGuides and Exhibits to default settings

- app/assets/stylesheets/modules/masthead.scss
- app/views/shared/_header_navbar.html.erb
> a11y fixes for Search dropdown

- app/services/library_website_api_search_service.rb
> Adds a result count to Libweb API results

- app/views/search/_module_heading.html.erb
- config/locales/en.yml
> Remove "See all results button" for zero results

- app/services/search_service.rb
Closes #393
Bumping up timeouts for sloooooow SearchWorks days
> Bump timeout up to 30 seconds

- app/views/shared/_sub_navbar.html.erb
👍. This has been approved for deployment on 12/13
> Bump Access info to 2022

- config/locales/en.yml
> Configure no results link for lib guides

- app/assets/stylesheets/modules/subnavbar.scss
- app/views/shared/_sub_navbar.html.erb
Part of https://github.com/sul-dlss/SearchWorks/issues/2827
> Remove Access menu item

- Gemfile
- Gemfile.lock
- app/assets/javascripts/custom_quick_search.js.erb
- app/assets/javascripts/toggleableResults.js
- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
- app/views/search/_module.html.erb
- app/views/search/_see_all.html.erb
- app/views/shared/_header_navbar.html.erb
This will also enable us to switch to dart sass and off the deprecated libsass
> Upgrade to font-awesome 5.  Add missing aria-hidden tags

- .rubocop.yml
- .rubocop_todo.yml
- app/views/shared/_more_search_tools.html.erb
- spec/features/homepage_spec.rb
> Update link for search tools

- app/views/shared/_services_menu.html.erb
Ref https://github.com/sul-dlss/SearchWorks/issues/3465
> Remove the find a subject specialist link

- app/assets/stylesheets/modules/stanford-only.scss
> fixes stanford only icon not showing up

- app/assets/stylesheets/modules/global-footer.scss
> fix footer

- app/assets/stylesheets/modules/subnavbar.scss
update button css to have caret match size on searchworks and update to rotate based on dropdown.
closes #641
> update css to match searchworks

- Gemfile
- Gemfile.lock
- config/initializers/rack_attack.rb
(I completely made these limits up based on what seems like reasonable usage.)
> Add rack-attack to bento

- app/controllers/search_controller.rb
- app/services/search_service.rb
- config/initializers/rack_attack.rb
... and don't bother EDS with the initial query. It never responds fast enough.
> Increase throttling to catch more bots

- app/services/abstract_search_service.rb
- config/settings.yml
- spec/services/abstract_search_service_spec.rb
Pending https://github.com/sul-dlss/SearchWorks/pull/4337
> Add a guest flag instead of faking an X-Forward-For header.

- app/assets/javascripts/custom_quick_search.js
> Guard against pages without any timeout spinners.

- app/assets/stylesheets/identity/bootstrap-variables.scss
- app/views/layouts/application.html.erb
The component library uses Source Sans 3
> Stop using Source Sans Pro

- app/assets/images/archive.svg
- app/assets/images/file.svg
- app/assets/images/folder.svg
- app/searchers/quick_search/application_searcher.rb
- app/searchers/quick_search/archives_searcher.rb
- app/searchers/quick_search/article_searcher.rb
- app/searchers/quick_search/catalog_searcher.rb
- app/searchers/quick_search/earthworks_searcher.rb
- app/searchers/quick_search/exhibits_searcher.rb
- app/searchers/quick_search/lib_guides_searcher.rb
- app/searchers/quick_search/library_website_api_searcher.rb
- app/services/archives_search_service.rb
- app/views/search/_module_heading.html.erb
- app/views/search/_result_details.html.erb
- app/views/search/_see_all.html.erb
- config/locales/en.yml
- config/settings.yml
- spec/fixtures/archives.json
- spec/services/archives_search_service_spec.rb
- spec/views/search/_module_heading.html.erb_spec.rb
> Add Archives searcher

- app/assets/stylesheets/modules/masthead.css
> update search box to better match figma

- app/views/pages/home.html.erb
> Change title wording

- app/assets/stylesheets/modules/results.css
- app/views/search/_result_details.html.erb
> Set font-weight and line-height on result title

- app/assets/stylesheets/modules/results.css
- app/views/search/index.html.erb
https://github.com/user-attachments/assets/3155cd33-d7ba-434e-8e33-a6d2cd3a40dc
> Add a placeholder when loading searchers.

- app/services/abstract_search_service.rb
This seems like a regression from #831, maybe?
> url is now a method.

- config/settings.yml
> Don't filter rows for archives query_url

- app/assets/stylesheets/modules/masthead.css
Fixes #903
Note, this is not supported by Firefox.
> Set a clear search icon and give apprpriate margin

- app/models/search_presenter.rb
- app/models/service.rb
- app/views/pages/home.html.erb
- app/views/search/_module.html.erb
- app/views/search/failed_search.html.erb
- config/locales/en.yml
- config/settings.yml
- spec/features/homepage_spec.rb
- spec/requests/lib_guides_mini_bento_spec.rb
- spec/views/search/_module_heading.html.erb_spec.rb
> Use the same key for i18n, enabled searchers, the url param, and settings

- app/models/article_result.rb
- app/models/catalog_result.rb
- app/services/article_search_service.rb
- app/services/catalog_search_service.rb
- app/views/article_results/_article_result.html.erb
- app/views/catalog_results/_catalog_result.html.erb
- spec/services/article_search_service_spec.rb
- spec/views/article_results/_article_result_spec.html.erb_spec.rb
From https://github.com/sul-dlss/SearchWorks/pull/5976
> Parse structured link data instead of the HTML
