spec/searchers/quick_search/article_searcher_spec.rb, spec/searchers/quick_search/catalog_searcher_spec.rb, spec/services/article_search_service_spec.rb, spec/services/catalog_search_service_spec.rb
```
QuickSearch::CatalogSearcher
should be a kind of CatalogSearchService::Response
should be a kind of QuickSearch::Searcher
should be a kind of Array
CatalogSearchService
should be a kind of CatalogSearchService::Response
should be a kind of AbstractSearchService
ArticleSearchService
should be a kind of AbstractSearchService
should be a kind of ArticleSearchService::Response
QuickSearch::ArticleSearcher
should be a kind of QuickSearch::Searcher
should be a kind of Array
should be a kind of ArticleSearchService::Response
Finished in 0.03323 seconds (files took 3.27 seconds to load)
10 examples, 0 failures
```
=> some initial super simple specs

app/assets/stylesheets/quick_search_overrides.scss, app/views/layouts/quick_search/_search_form.html.erb, app/views/layouts/quick_search/application.html.erb
This also solves a bug where the columns when first loading a search result would push together.
Part of the work on #12 
This moves the search bar styling and responsiveness to be more "Bootstrappy". @camillevilla I would love your thoughts on this b/c of your work on some of the styling stuff already.
=> modify responsiveness of searchbar

app/views/layouts/quick_search/_found_types.html.erb, app/views/quick_search/search/_module.html.erb, spec/features/searcher_anchors_spec.rb
=> Display total counts of searchers in the searcher anchors

app/views/layouts/quick_search/_search_form.html.erb, config/locales/en.yml
Closes #54 
This PR replaces the placeholder text provided by QuickSearch with "catalog + articles + website + more"
=> Add custom placeholder text

app/assets/images/search.svg, app/assets/stylesheets/homepage.scss, app/views/quick_search/pages/home.html.erb, app/views/quick_search/search/index.html.erb, app/views/shared/_more_search_tools.html.erb, spec/features/homepage_spec.rb
=> add More search tools panel to search results and homepage

app/assets/stylesheets/application.scss, app/assets/stylesheets/searcher-anchors.scss, app/views/layouts/quick_search/_found_types.html.erb, config/locales/en.yml, spec/features/jumplinks_spec.rb, spec/features/searcher_anchors_spec.rb
Closes #42 
This PR:
- uses shortened names for search anchors
- adds Yewno to the search anchors
- adds some responsive behavior fixes
=> Add Yewno to search anchors and fix responsive behavior

app/assets/stylesheets/base.scss, app/assets/stylesheets/homepage.scss, app/views/quick_search/pages/home.html.erb
This PR fixes #60.
@jvine is the font-size for the h3 headers ok? it's not specified in [base.scss](https://github.com/sul-dlss/sul-bento-app/blob/60-cleanup/app/assets/stylesheets/base.scss#L35-L39)
=> change wording/styling for SearchWorks parity

config/deploy.rb
This PR removes the `config/secrets.yml` files from shared_configs as puppet now manages this data (via the `SECRET_KEY_BASE` environment variable that the checked in version of `config/secrets.yml` uses for production). See https://github.com/sul-dlss/operations-tasks/issues/778 for discussion
Requires the following PRs to be merged:
- https://github.com/sul-dlss/shared_configs/pull/381
- https://github.com/sul-dlss/shared_configs/pull/382
=> secrets are now managed by puppet

app/services/abstract_search_service.rb, app/services/library_website_search_service.rb, spec/fixtures/library.stanford.edu/2.html, spec/services/library_website_search_service_spec.rb
This PR fixes #67. It updates the abstract class so that the HighlightedFacetItem can be overriden by the service subclasses.
The library website facets now have the search terms parsed out of the Drupal URL while keeping their label (e.g., "News (archived)" is actually the search term "type:news").
=> override HighlightedFacetItem to handle website facet queries

app/assets/stylesheets/base.scss, app/assets/stylesheets/results.scss, app/views/quick_search/search/_see_all.html.erb
Addresses part of #68 , includes pre-requisite commits from #74 
- Changes base font size from Chrome default 16px to Searchworks-y 15px
- Reduces vertical spacing between result elements
- adds button styling to "See all results" links
- increases `font-weight` for `<h2>` to 400
=> Stylin': base font size and vertical spacing

config/routes.rb
This is so our reverse proxy on library.stanford.edu works appropriately.
=> Mount quicksearch engine under "/all"

app/assets/javascripts/yewno.js, app/assets/stylesheets/modules/buttons.scss, app/assets/stylesheets/yewno.scss, app/views/quick_search/search/index.html.erb
Closes #83 
This PR adds some styling to differentiate the Yewno module from Stanford results:
- black border-top for the module
- black background for the link out to Yewno
- subtitle for the Yewno module
Unfortunately, I don't have much leeway with the "Explore other concepts" link. It gets positioned absolutely by Yewno's external stylesheet. I have two options for fixes below:
=> Add differentiating styles to Yewno module

config/routes.rb
This PR fixes #81 by disabling the appstats routes (redirects them to /all).
=> redirect all of the appstats page routes

config/routes.rb
Closes #88 
This PR overrides the 'About' page baked into the `quick_search` gem by redirecting `/all/about` to `/all`.
=> Redirect 'about' page to home page

app/assets/stylesheets/modules/results.scss, app/views/quick_search/search/_module.html.erb, app/views/quick_search/search/_module_heading.html.erb, app/views/quick_search/search/_see_all.html.erb, spec/features/searcher_anchors_spec.rb
Closes #84 
This PR: 
- moves the "See all results" button to the top of the module ands makes it more visible to users
- Changes buttons from 'See all Articles+ results'  to 'See all results'
=> Move search results button

config/quick_search_config.yml
This PR fixes #85 
It's sub-optimal as bento-stage will send traffic too (i.e., we're not using shared_configs for the quicksearch yml).
=> add our google_analytics_tracking_id

app/assets/javascripts/application.js, app/assets/javascripts/custom_quick_search.js.erb, app/views/layouts/quick_search/application.html.erb, vendor/assets/javascripts/jquery-migrate-3.0.0.js
Closes #71 
This PR not only fixes the JavaScript console errors, but now does the following:
- stops loading two different versions of jQuery 😢 
- removes loading of admin only quick search javascript resources
- d3
- lodash
- removes loading of jquery-ui css and js
See https://github.com/NCSU-Libraries/quick_search/blob/master/app/assets/javascripts/quick_search.js.erb for all dependencies and compare with `app/assets/javascripts/custom_quick_search.js.erb`
=> Fix js errors, and do not load everything

app/views/quick_search/search/_module.html.erb, spec/views/quick_search/search/_module_heading.html.erb_spec.rb
Hopefully fixes #97 
- Error: modules with zero search results were not loading properly. After #92, the `_module_heading` partial requires that a value  `total` and `searcher` be passed in. No `searcher` value was passed for in the case of `searcher.results.blank?`. 
- Fix: add `searcher` values to remaining instances of `render partial: 'module_heading'`
- Adds a view spec for` _module_heading.html.erb`
- [prod](https://library.stanford.edu/all/?utf8=%E2%9C%93&q=%22Rimsky-Korsakov%2C%20Nikolay%2C%201844-1908.%20Skazanie%20o%20nevidimom%20grade%20Kitezhe%20i%20deve%20Fevronii.%22)
- [localhost](http://localhost:3000/all/?utf8=%E2%9C%93&q=%22Rimsky-Korsakov%2C%20Nikolay%2C%201844-1908.%20Skazanie%20o%20nevidimom%20grade%20Kitezhe%20i%20deve%20Fevronii.%22)
=> Bugfix: module heading template missing value for searcher

app/services/library_website_search_service.rb
This PR is connected to #102 and it should handle no result pages better. I'm not able to reproduce the problem as when I get no results from the library website the `doc.css('.search-results .views-row')` search fails (as expected) so it shouldn't even get into the inner loop. Nevertheless, this PR does some error checking to avoid the NilClass exceptions.
=> handle error cases when scraping library website hits

app/views/quick_search/search/_result_details.html.erb, config/settings.yml, spec/views/quick_search/search/_result_details.html.erb_spec.rb
=> Truncate result descriptions to 150 characters.

app/searchers/quick_search/article_searcher.rb, app/searchers/quick_search/catalog_searcher.rb, app/searchers/quick_search/library_website_searcher.rb, app/services/abstract_search_service.rb
Fixes #111 
This PR fixes an issue where ampersands were not being escaped. 
https://library.stanford.edu/all/?utf8=%E2%9C%93&q=Sun+%26+steel
Catalog link: https://searchworks.stanford.edu/?q=Sun%20&%20steel
http://localhost:3000/all/?utf8=%E2%9C%93&q=Sun+%26+steel
Catalog link: https://searchworks.stanford.edu/?q=Sun%20&%20steel
=> Use CGI.escape for query strings

app/views/shared/_services_menu.html.erb, app/views/shared/_sul_footer.html.erb
Fixes #154
This PR adds links to the Searchworks status dashboard in both the Library Services menu and the footer.
=> Add links to Searchworks status dashboard

app/views/shared/_services_menu.html.erb, app/views/shared/_sul_footer.html.erb
This PR points our status dashboard link to [library-status.stanford.edu](library-status.stanford.edu/)
=> Change status dashboard URL

app/views/shared/_services_menu.html.erb, app/views/shared/_sul_footer.html.erb
Updated "SearchWorks status" to "System status" in menu & footer to match SW and website.
=> System status wording

app/assets/stylesheets/modules/global-alert.scss, app/assets/stylesheets/sul-bento.scss, app/views/layouts/quick_search/application.html.erb, app/views/shared/_global_alert.html.erb, config/locales/en.yml, config/settings.yml
Closes #233 
This PR: 
- adds a configurable area for global alerts
- sets the alert to this year's winter closure message
=> Add global alert configurable via settings

app/searchers/quick_search/lib_guides_searcher.rb, app/services/lib_guides_search_service.rb, app/views/quick_search/search/index.html.erb, config/locales/en.yml, config/quick_search_config.yml, config/settings.yml, config/settings/test.yml, spec/features/lib_guides_spec.rb, spec/searchers/quick_search/lib_guides_searcher_spec.rb, spec/services/lib_guides_search_service_spec.rb
Part of #295 
This sets up the basic building blocks for implementing and working on lib guides. I'm not exactly sure of the page layout, but this is feature flagged so perhaps we can iterate on that?
=> Adds a basic Lib Guide search functionality

app/assets/stylesheets/modules/results.scss, app/assets/stylesheets/sul-variables.scss, app/services/abstract_search_service.rb, app/services/catalog_search_service.rb, app/views/quick_search/search/_result_details.html.erb
Closes #306 
This is assuming sul-dlss/SearchWorks#2512 is shipped and available
=> Pull in temporary access links from the catalog API.

app/assets/stylesheets/modules/masthead.scss
=> Don't remove the focus outline for the search scope dropdown

app/assets/javascripts/application.js, app/assets/javascripts/toggleableResults.js, app/assets/stylesheets/modules/results.scss, app/searchers/quick_search/exhibits_searcher.rb, app/services/exhibits_search_service.rb, app/views/quick_search/search/_module.html.erb, app/views/quick_search/search/_module_heading.html.erb, app/views/quick_search/search/_result_with_thumbnail.html.erb, app/views/quick_search/search/index.html.erb, config/locales/en.yml, config/settings.yml, config/settings/test.yml, spec/features/exhibits_spec.rb, spec/searchers/quick_search/exhibits_searcher_spec.rb, spec/services/exhibits_search_service_spec.rb
Closes #298
...
_**Note:** I locally configured the threshold to 2 just to get the toggle functionality showing (since we're currently limiting the API results to 5, which will be addressed on the next deploy to Exhibits)._
=> Add an Exhibits bento box

app/searchers/quick_search/lib_guides_searcher.rb, app/services/lib_guides_search_service.rb, config/locales/en.yml, config/settings.yml, spec/searchers/quick_search/lib_guides_searcher_spec.rb
=> Enable LibGuides results to be toggleable.

app/views/quick_search/pages/home.html.erb, app/views/quick_search/search/index.html.erb, app/views/shared/_more_search_tools.html.erb, config/locales/en.yml, spec/views/quick_search/search/_module_heading.html.erb_spec.rb
Closes #342
- Updates searcher descriptions per feedback from OEG.
- consolidates some of these strings into existing i18n keys
🤞 This should clear the way for some refactoring of this view!
!homepage with new text](https://user-images.githubusercontent.com/5402927/89598711-52e56e00-d812-11ea-95b2-d698243425c7.png)
=> Update searcher description text

app/searchers/quick_search/article_searcher.rb, app/searchers/quick_search/catalog_searcher.rb, app/services/article_search_service.rb, app/services/catalog_search_service.rb, app/views/quick_search/pages/home.html.erb, app/views/quick_search/search/index.html.erb, config/settings.yml, spec/features/homepage_spec.rb
Closes #338
Closes #327 
This PR:
- moves around catalog and article settings so they're nice n' readable like exhibits API and libweb API
- Adds the `ENBALED_SEARCHERS` pattern to catalog and articles
=> Apply new config patterns to catalog and articles

app/assets/stylesheets/modules/searcher-anchors.scss, app/views/layouts/quick_search/_found_types.html.erb
Fixes #345 
I've used the h3 fontsize which is different than the `em` specified in #345. The size in #345 is the h4 size.
=> Update dl to use a ul with nav component fixes #345

app/assets/stylesheets/modules/results.scss, app/views/quick_search/search/_result_with_thumbnail.html.erb
=> Update result styling

app/searchers/quick_search/library_website_api_searcher.rb, app/services/library_website_api_search_service.rb, app/views/quick_search/search/index.html.erb, config/locales/en.yml, config/settings.yml, config/settings/test.yml, spec/searchers/quick_search/library_website_api_searcher_spec.rb, spec/services/library_website_api_search_service_spec.rb
Fixes #104  part of evaluation in #105 
Analysis of current JSON api here: https://github.com/sul-dlss/sul-bento-app/issues/105#issuecomment-668794602
This is built in a way so that it could be released via a configuration.
=> Enables support for new library website JSON api

app/assets/stylesheets/modules/libweb.scss, app/assets/stylesheets/sul-bento.scss, app/services/library_website_api_search_service.rb, app/views/quick_search/search/_result_details.html.erb, spec/services/library_website_api_search_service_spec.rb
Closes #51, see designs in #15
This PR uses the shiny new libweb API to adds breadcrumbs to each Library website result.
I think this is ok for a first implementation, but when we have some time again it's worth circling back for accessibility review of this particular component (ticketed: #379)
- [w3: breadcrumb pattern](https://www.w3.org/TR/wai-aria-practices-1.1/examples/breadcrumb/index.html)
- decorative elements added via markup but hidden from screenreader with `aria-hidden`
- I tried using a CSS `::after`. In VoiceOver it didn't announce the &raquo;, but it made the `<ol>` twice as long?? (1 of 8 links!)
- I decided not to use the recommended `<nav>` tag here 
- the w3 pattern breadcrumb assumes that the breadcrumb is for the current page and that there's only 1 per page
- The …
=> Add breadcrumbs to libweb search results

app/services/library_website_api_search_service.rb, spec/services/library_website_api_search_service_spec.rb
=> Remove 'Home' from breadcrumbs to reduce noise

app/assets/stylesheets/modules/subnavbar.scss, app/views/shared/_services_menu.html.erb, app/views/shared/_sub_navbar.html.erb, spec/views/shared/_sub_navbar.html.erb_spec.rb
Closes #397
This PR:
- adds a link to our COVID-19 status page
- renames the `Library services` menu to `Help`
- removes several links and subheadings
- cleans up some unused CSS, updates dropdown classes to new Bootstrappy 4.3 versions
I'm deploying this to bento stage if anyone wants to take a second look there.
=> Update Library services menu

app/services/catalog_search_service.rb
Or, at least, if we do try to parse the xml, we'll find it is no longer in the search responses and hasn't been for awhile 🤷‍♂️
=> Remove fallback path to marcxml that we never go on

README.md, app/controllers/search_controller.rb, app/services/search_service.rb
1. Updates to readme to show how you can run a search manually on the rails console (I found this useful)
2. Noted when running the app locally that I was seeing some errors in the logs like this:
```
FAILED SEARCH: catalog | covid-19 | wrong number of arguments (given 2, expected 1)
FAILED SEARCH: library_website_api | covid-19 | wrong number of arguments (given 2, expected 1)
FAILED SEARCH: exhibits | covid-19 | wrong number of arguments (given 2, expected 1)
FAILED SEARCH: lib_guides | covid-19 | wrong number of arguments (given 2, expected 1)
FAILED SEARCH: article | covid-19 | wrong number of arguments (given 2, expected 1)
```
When I looked at the method signatures, it seems like they didn't match (even though the app was working ok in the browser).  Made changes, errors in log went …
=> method signatures didn't seem to match

app/assets/javascripts/yewno.js, app/assets/stylesheets/modules/yewno.scss
Fixes #505 
We hide a bunch text to clean up the display, and we hide the discover link because they took away the configuration that sends users through ezproxy.
---
before our styling hacks:
=> Update to the new Yewno widget

app/assets/stylesheets/application/deja-vu-font.scss
It is no longer necessary and prevents the font from loading
This fixes the following error:
```
Unknown descriptor ‘font-url(’ in @font-face rule.  Skipped to next declaration.
```
=> Stop using font-url

app/views/layouts/application.html.erb, config/settings.yml
Relates to https://github.com/sul-dlss/sul-bento-app/issues/539
=> changing to GA4 support, removing older tag manager code

app/javascript/application.js, app/javascript/toggleableResults.js, app/views/search/_module.html.erb
@jcoyne after I merged https://github.com/sul-dlss/sul-bento-app/pull/698 I noticed that `toggleableResults` wasn't working so all the guide results are being shown on the results page instead of getting truncated. This PR gets it working, but maybe there's a better fix?
Before:
After:
=> Fix guide results toggle

app/searchers/quick_search/lib_guides_searcher.rb, app/services/lib_guides_search_service.rb, spec/searchers/quick_search/lib_guides_searcher_spec.rb
closes #748 
**No results**
**55 results**
**223 results, which we aren't able to easily get the correct number**
=> make guides not toggleable, fix guides results total display

config/initializers/rack_attack.rb
... now that the puppet change is in.
Revert "Comment out redis until the iptables are updated."
This reverts commit 12e4b76fedc239f8b4bb165e2add252ee9b651ca.
=> Re-enable redis for rack-attack

app/views/search/_found_types.html.erb, app/views/search/index.html.erb
=> Adjust padding on search result page

.rubocop.yml, spec/features/homepage_spec.rb, spec/features/search_results_spec.rb, spec/services/exhibits_search_service_spec.rb, spec/services/library_website_api_search_service_spec.rb
I don't think we aspire to lots of rspec expectations in a single test.
=> Reduce the allowed RSpec/MultipleExpectations

app/assets/stylesheets/modules/results.css, app/views/search/_module_heading.html.erb, spec/features/search_results_spec.rb
=> Add button padding

app/views/search/_module_heading.html.erb
This fixes a regression where we are currently showing a button for "0" results
Before
After
=> Don't show the button if there are zero results

app/views/search/_result_details.html.erb
=> Fix icon position

app/views/search/_result_details.html.erb
=> Align icon to the first line of text in the physical description

app/views/shared/_header.html.erb
I think `navbars` was a typo; bootstrap uses the `navbar` class to opt-out of the default popper behavior (related to #825)
=> Fix a typo to get the default bootstrap navbar/dropdown behavior.

config/routes.rb, spec/features/homepage_spec.rb
Sometimes the homepage_feature_spec was getting routed to the show route.  This conditional makes the routing more deterministic.
=> Prevent flappy feature spec

app/assets/stylesheets/component-library-overrides.css
=> Don't use blue as the active cover on dropdown items

app/views/pages/home.html.erb
This helps avoids an awkward re-flow when switching from xl to xxl breakpoints:
current xl:
xxl:
After, this change isn't as dramatic (and xxl looks substantially the same):
=> Use the grid system to create space between the main search tools and the aside

app/assets/stylesheets/modules/masthead.css
=> add link underlining for focused menu arrows

app/helpers/application_helper.rb, app/models/search_result.rb, app/services/article_search_service.rb, app/services/catalog_search_service.rb, app/views/search/_result_details.html.erb, spec/views/search/_result_details.html.erb_spec.rb
Closes #832
Some of these details were discussed with @dbranchini outside of the issue.
=> Update result formats to match design

app/services/abstract_search_service.rb, app/services/archives_search_service.rb, app/services/article_search_service.rb, app/services/catalog_search_service.rb, app/services/earthworks_search_service.rb, app/services/exhibits_search_service.rb, app/services/lib_guides_search_service.rb, app/services/library_website_api_search_service.rb, spec/features/search_results_spec.rb, spec/services/lib_guides_search_service_spec.rb
Rather than a 200 status with no results, lib_guides returns a 404 reponse. This change adjusts the response so that we still see 'No results' on the page.
=> Handle empty results for lib_guides

app/controllers/search_controller.rb, app/models/search_presenter.rb, app/views/search/_see_all.html.erb, app/views/search/show.json.jbuilder, config/routes.rb, spec/views/search/_module_heading.html.erb_spec.rb
See #750 and #822 for the whole saga. This changes the bento label back to "See all 100+ lib guides results", which we seem to have lost in #822 ?
=> Extract SearchPresenter#formatted_total to handle libguides weirdness.

app/views/search/index.html.erb
=> Fix aside padding after guides

app/views/search/_result_details.html.erb
and just guard the lines we actually care about (e.g. things blow up currently if there's `result.physical` but no `result.icon`, which apparently can happen with archives results.)
Fixes #899
=> Remove a wrapping condition (that was slightly inaccurate) 

app/views/search/index.html.erb
Maybe a solution to the spacing aspect of https://github.com/sul-dlss/sul-bento-app/issues/903?
Before
After
=> Add padding to the end of the search input

app/models/archives_result.rb, spec/models/archives_result_spec.rb
See https://archives.stanford.edu/catalog/m1047_aspace_ref52_7yo, and presumably others.
=> Some archives results have mixed-case types.

app/javascript/application.js, app/views/search/index.html.erb
The current implementation breaks the top links for website + guides (because the DOM ids are duplicated in the `#modules` and the `aside`). This PR just re-parents the modules if it needs to 🤷‍♂️
=> Handle the 'aside' modules without duplicating content.

app/views/search/_see_all.html.erb
See all for the library website is gives `content missing` when clicked.
=> Disable turbo for see all results link

app/views/exhibits_results/_exhibits_result.html.erb
=> Prevent thubmnails from using the full width at small viewports

app/views/exhibits_results/_exhibits_result.html.erb
Align the title with the top of the thumbnail.
=> Remove top padding for exhibits

app/views/pages/home.html.erb, app/views/shared/_sul_footer.html.erb
I don't know if this belongs in the component library, or is a consequence of how we're doing bento, but this PR gets the SUL footer to line up better in smaller breakpoints:
Before:
After:
=> Get the SUL footer + body content to all line up at xs breakpoints
